### ISSUE TITLE
Anonymous user and rights

### ISSUE THREAD

**Issue by sookoll** [nliautaud/pico-users#17]
There should be anon built-in user, so there is possibility to grant anonymous access to page in directory, which is restricted.

```
users:
    editors:
        user1: passhash
rights:
    folder: editors
    folder/public: anon

```

or some other way to exclude some page from restrictions
